import type { Reality } from "./types";

export const REALITIES_1: Reality[] = [
  // SELF & DISCIPLINE
  { theme: "self", truth: "Nobody is coming to save you.", detail: "People can help, encourage and open doors, but no one will want your life more than you do. The moment you stop waiting for rescue, you start building.", action: "Name one thing you've been waiting on someone else to fix, and take the first step yourself today." },
  { theme: "self", truth: "Motivation is unreliable; discipline is not.", detail: "Most days you won't feel like it. The people who get ahead do the work anyway, because feelings follow action far more often than action follows feelings.", action: "Pick the one task you've been avoiding and do just the first 10 minutes." },
  { theme: "self", truth: "You become what you repeatedly do.", detail: "Your life is the sum of your ordinary days. One great day changes little; a thousand decent days change everything.", action: "Choose one small daily action that matches who you want to be, and log it as a habit." },
  { theme: "self", truth: "Comfort is the enemy of growth.", detail: "Everything you want is on the other side of some discomfort — a hard conversation, an early morning, a difficult skill. Choosing comfort every time quietly shrinks your life.", action: "Do one uncomfortable thing today on purpose." },
  { theme: "self", truth: "You can't hate yourself into a better version of you.", detail: "Shame paralyses; honest self-respect moves you forward. Hold yourself to a high standard, but talk to yourself like someone you're responsible for helping.", action: "Rewrite one harsh thought about yourself into something honest but kind." },
  { theme: "self", truth: "What you tolerate, you keep.", detail: "Bad habits, unhealthy relationships and low standards stay as long as you put up with them. Change begins the day you stop accepting what you know is wrong.", action: "Write down one thing you've been tolerating and decide your line on it." },
  { theme: "self", truth: "Your excuses are usually valid — and still don't matter.", detail: "You may really be tired, busy or under-resourced. The outcome doesn't care. The question isn't whether the obstacle is real; it's what you'll do anyway.", action: "Take your most common excuse and plan a smaller version of the task that works around it." },

  // TIME & MORTALITY
  { theme: "time", truth: "Your time is limited, and you don't know how limited.", detail: "Tomorrow isn't promised. That's not a reason for fear, but for clarity — it strips away what doesn't matter.", action: "Ask: if I had one year left, what would I stop doing? Stop one of those things." },
  { theme: "time", truth: "Someday is not a day of the week.", detail: "Plans that live in 'someday' rarely happen. A goal without a date is a wish.", action: "Put a real deadline on one goal that's been sitting open-ended." },
  { theme: "time", truth: "How you spend your days is how you spend your life.", detail: "Scrolling for an hour a day is over two weeks a year. Small leaks add up to whole seasons.", action: "Check your screen time today and choose one app to cut back." },
  { theme: "time", truth: "Busy is not the same as productive.", detail: "You can stay busy all day and move nothing important forward. Progress comes from doing the right things, not the most things.", action: "Write your three most important tasks for tomorrow before you sleep." },
  { theme: "time", truth: "The years pass slowly and then all at once.", detail: "The habits you start at 25 compound by 35 — for better or worse. Decades are built from very ordinary Tuesdays.", action: "Picture yourself in 10 years if nothing changes. Decide what has to change now." },

  // MONEY
  { theme: "money", truth: "It's not what you earn, it's what you keep.", detail: "Plenty of high earners are broke; plenty of modest earners build wealth. Spending habits decide the outcome more than salary does.", action: "Automate a fixed amount into savings on the day you get paid." },
  { theme: "money", truth: "Debt is a claim on your future self.", detail: "Every loan spends money you haven't earned yet. Some debt builds your life; most debt just rents you a lifestyle you can't afford.", action: "List your debts smallest to largest and put any extra shilling toward the first one." },
  { theme: "money", truth: "Lifestyle inflation silently eats raises.", detail: "When income rises, spending quietly rises to match. The only way to get ahead is to let your savings grow faster than your lifestyle.", action: "Commit to saving at least half of your next raise or bonus." },
  { theme: "money", truth: "An emergency will come. The only question is whether you're ready.", detail: "Medical bills, job loss, family needs — they're not 'if' but 'when'. An emergency fund turns a crisis into an inconvenience.", action: "Start (or top up) an emergency fund plan on the Savings page." },
  { theme: "money", truth: "Nobody cares about your money as much as you do.", detail: "Not banks, not salespeople, not 'opportunities' promising quick returns. If it sounds too good to be true, it is.", action: "Before your next big purchase or investment, wait 48 hours and ask one trusted person." },
  { theme: "money", truth: "Impressing people is expensive.", detail: "Many financial struggles come from trying to look successful rather than be successful. Real wealth is often quiet.", action: "Identify one expense you make mainly for how it looks, and cut it." },
  { theme: "money", truth: "Generosity is part of wealth, not the opposite of it.", detail: "Holding money too tightly shrinks your heart. Giving keeps money a tool and not a master.", action: "Plan one intentional act of giving this month, however small." },

  // RELATIONSHIPS
  { theme: "relationships", truth: "You are shaped by the people closest to you.", detail: "Their habits, ambitions and standards become your normal. Choose your circle as carefully as you choose your goals.", action: "Think of the five people you spend the most time with. Is there one you should see more, or less?" },
  { theme: "relationships", truth: "Not everyone will like you, and that's fine.", detail: "Trying to please everyone guarantees you'll disappoint yourself. Respect matters more than approval.", action: "Notice one decision you're making only to be liked, and choose what's right instead." },
  { theme: "relationships", truth: "People show you who they are through what they do, not what they say.", detail: "Consistent behaviour over time is the truth about someone. Believe the pattern, not the promise.", action: "When someone's words and actions don't match, trust the actions." },
  { theme: "relationships", truth: "Some people are in your life for a season, not a lifetime.", detail: "Outgrowing people isn't betrayal. You can honour what a relationship was and still let it change.", action: "Release, with gratitude, one relationship you've been forcing to stay the same." },
  { theme: "relationships", truth: "Unspoken expectations turn into resentment.", detail: "People can't meet needs they don't know about. Clear, kind communication prevents most conflict.", action: "Tell someone close to you one thing you need, plainly and without blame." },
  { theme: "relationships", truth: "The people who matter most are often the easiest to neglect.", detail: "Family and old friends are always 'there', so they get your leftover time. One day, they won't be there.", action: "Call or visit someone you love this week — just to connect." },
  { theme: "relationships", truth: "Forgiveness frees you more than the other person.", detail: "Holding a grudge is like carrying a weight for someone who has already walked away. Forgiveness doesn't excuse the wrong; it releases you from it.", action: "Write down one grudge you're carrying and pray or reflect on letting it go." },

  // WORK & CAREER
  { theme: "work", truth: "Skills pay the bills; reputation opens the doors.", detail: "Being good at what you do gets you started. Being known as reliable, honest and easy to work with is what keeps opportunities coming.", action: "Deliver one thing this week earlier or better than expected." },
  { theme: "work", truth: "No one owes you a career.", detail: "Degrees and certificates get you in the room. What you do in the room — and what you keep learning — decides where you go.", action: "Spend 30 minutes this week learning a skill your next role will need." },
  { theme: "work", truth: "Your employer can replace you; your family can't.", detail: "Work hard, but don't sacrifice your health and relationships for a company that would fill your seat in a month.", action: "Set one clear boundary between work time and personal time this week." },
  { theme: "work", truth: "Doing what you're asked makes you useful. Solving problems no one asked you to makes you valuable.", detail: "Initiative is rare. People who see what needs to be done and do it stand out quickly.", action: "Find one small problem at work or home and fix it without being asked." },
  { theme: "work", truth: "Being early is being on time.", detail: "Reliability is a quiet superpower. People trust those who show up when and how they said they would.", action: "Arrive five minutes early to everything this week." },
  { theme: "work", truth: "Your network is built long before you need it.", detail: "Relationships built only when you need something feel transactional. Invest in people when you want nothing from them.", action: "Reach out to one person in your field just to encourage or thank them." },
];
