// Canonical 66-book order, matched 1:1 to the abbrev order in kjv.json.
export const BOOK_META: { abbrev: string; name: string; testament: "old" | "new" }[] = [
  { abbrev: "gn", name: "Genesis", testament: "old" },
  { abbrev: "ex", name: "Exodus", testament: "old" },
  { abbrev: "lv", name: "Leviticus", testament: "old" },
  { abbrev: "nm", name: "Numbers", testament: "old" },
  { abbrev: "dt", name: "Deuteronomy", testament: "old" },
  { abbrev: "js", name: "Joshua", testament: "old" },
  { abbrev: "jud", name: "Judges", testament: "old" },
  { abbrev: "rt", name: "Ruth", testament: "old" },
  { abbrev: "1sm", name: "1 Samuel", testament: "old" },
  { abbrev: "2sm", name: "2 Samuel", testament: "old" },
  { abbrev: "1kgs", name: "1 Kings", testament: "old" },
  { abbrev: "2kgs", name: "2 Kings", testament: "old" },
  { abbrev: "1ch", name: "1 Chronicles", testament: "old" },
  { abbrev: "2ch", name: "2 Chronicles", testament: "old" },
  { abbrev: "ezr", name: "Ezra", testament: "old" },
  { abbrev: "ne", name: "Nehemiah", testament: "old" },
  { abbrev: "et", name: "Esther", testament: "old" },
  { abbrev: "job", name: "Job", testament: "old" },
  { abbrev: "ps", name: "Psalms", testament: "old" },
  { abbrev: "prv", name: "Proverbs", testament: "old" },
  { abbrev: "ec", name: "Ecclesiastes", testament: "old" },
  { abbrev: "so", name: "Song of Solomon", testament: "old" },
  { abbrev: "is", name: "Isaiah", testament: "old" },
  { abbrev: "jr", name: "Jeremiah", testament: "old" },
  { abbrev: "lm", name: "Lamentations", testament: "old" },
  { abbrev: "ez", name: "Ezekiel", testament: "old" },
  { abbrev: "dn", name: "Daniel", testament: "old" },
  { abbrev: "ho", name: "Hosea", testament: "old" },
  { abbrev: "jl", name: "Joel", testament: "old" },
  { abbrev: "am", name: "Amos", testament: "old" },
  { abbrev: "ob", name: "Obadiah", testament: "old" },
  { abbrev: "jn", name: "Jonah", testament: "old" },
  { abbrev: "mi", name: "Micah", testament: "old" },
  { abbrev: "na", name: "Nahum", testament: "old" },
  { abbrev: "hk", name: "Habakkuk", testament: "old" },
  { abbrev: "zp", name: "Zephaniah", testament: "old" },
  { abbrev: "hg", name: "Haggai", testament: "old" },
  { abbrev: "zc", name: "Zechariah", testament: "old" },
  { abbrev: "ml", name: "Malachi", testament: "old" },
  { abbrev: "mt", name: "Matthew", testament: "new" },
  { abbrev: "mk", name: "Mark", testament: "new" },
  { abbrev: "lk", name: "Luke", testament: "new" },
  { abbrev: "jo", name: "John", testament: "new" },
  { abbrev: "act", name: "Acts", testament: "new" },
  { abbrev: "rm", name: "Romans", testament: "new" },
  { abbrev: "1co", name: "1 Corinthians", testament: "new" },
  { abbrev: "2co", name: "2 Corinthians", testament: "new" },
  { abbrev: "gl", name: "Galatians", testament: "new" },
  { abbrev: "eph", name: "Ephesians", testament: "new" },
  { abbrev: "ph", name: "Philippians", testament: "new" },
  { abbrev: "cl", name: "Colossians", testament: "new" },
  { abbrev: "1ts", name: "1 Thessalonians", testament: "new" },
  { abbrev: "2ts", name: "2 Thessalonians", testament: "new" },
  { abbrev: "1tm", name: "1 Timothy", testament: "new" },
  { abbrev: "2tm", name: "2 Timothy", testament: "new" },
  { abbrev: "tt", name: "Titus", testament: "new" },
  { abbrev: "phm", name: "Philemon", testament: "new" },
  { abbrev: "hb", name: "Hebrews", testament: "new" },
  { abbrev: "jm", name: "James", testament: "new" },
  { abbrev: "1pe", name: "1 Peter", testament: "new" },
  { abbrev: "2pe", name: "2 Peter", testament: "new" },
  { abbrev: "1jo", name: "1 John", testament: "new" },
  { abbrev: "2jo", name: "2 John", testament: "new" },
  { abbrev: "3jo", name: "3 John", testament: "new" },
  { abbrev: "jd", name: "Jude", testament: "new" },
  { abbrev: "re", name: "Revelation", testament: "new" },
];

// A curated pool of well-known, encouraging verses (as "book chapter:verse")
// used to seed a richer "verse of the day" rotation. Falls back to a random
// verse from the whole Bible if this pool is ever empty.
export const FEATURED_REFERENCES: { book: string; chapter: number; verse: number }[] = [
  { book: "Jeremiah", chapter: 29, verse: 11 },
  { book: "Philippians", chapter: 4, verse: 13 },
  { book: "Proverbs", chapter: 3, verse: 5 },
  { book: "Proverbs", chapter: 3, verse: 6 },
  { book: "Psalms", chapter: 23, verse: 1 },
  { book: "Psalms", chapter: 46, verse: 1 },
  { book: "Isaiah", chapter: 41, verse: 10 },
  { book: "Joshua", chapter: 1, verse: 9 },
  { book: "Romans", chapter: 8, verse: 28 },
  { book: "Romans", chapter: 12, verse: 2 },
  { book: "2 Timothy", chapter: 1, verse: 7 },
  { book: "Matthew", chapter: 6, verse: 33 },
  { book: "Galatians", chapter: 6, verse: 9 },
  { book: "James", chapter: 1, verse: 2 },
  { book: "James", chapter: 1, verse: 5 },
  { book: "1 Corinthians", chapter: 10, verse: 13 },
  { book: "1 Corinthians", chapter: 13, verse: 4 },
  { book: "Hebrews", chapter: 11, verse: 1 },
  { book: "Hebrews", chapter: 12, verse: 1 },
  { book: "Colossians", chapter: 3, verse: 23 },
  { book: "Psalms", chapter: 37, verse: 4 },
  { book: "Psalms", chapter: 121, verse: 1 },
  { book: "Psalms", chapter: 121, verse: 2 },
  { book: "Ecclesiastes", chapter: 3, verse: 1 },
  { book: "Isaiah", chapter: 40, verse: 31 },
  { book: "John", chapter: 3, verse: 16 },
  { book: "John", chapter: 14, verse: 27 },
  { book: "Matthew", chapter: 11, verse: 28 },
  { book: "Philippians", chapter: 4, verse: 6 },
  { book: "Philippians", chapter: 4, verse: 7 },
];
