// A starter bank of quotes across categories. Fully editable afterward from
// the Quotes page — this just means you're not starting from zero.
export const STARTER_QUOTES: { text: string; author: string; category: string }[] = [
  { text: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln", category: "discipline" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Will Durant", category: "discipline" },
  { text: "The pain of discipline weighs ounces; the pain of regret weighs tons.", author: "Jim Rohn", category: "discipline" },
  { text: "You do not rise to the level of your goals. You fall to the level of your systems.", author: "James Clear", category: "systems" },
  { text: "It is not the mountain we conquer but ourselves.", author: "Edmund Hillary", category: "resilience" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb", category: "resilience" },
  { text: "Hard choices, easy life. Easy choices, hard life.", author: "Jerzy Gregorek", category: "discipline" },
  { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee", category: "focus" },
  { text: "Where your attention goes, your time goes.", author: "Idowu Koyenikan", category: "focus" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso", category: "action" },
  { text: "A year from now you may wish you had started today.", author: "Karen Lamb", category: "action" },
  { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar", category: "growth" },
  { text: "Growth is painful. Change is painful. But nothing is as painful as staying stuck somewhere you don't belong.", author: "N.R. Narayana Murthy", category: "growth" },
  { text: "Slow progress is still progress.", author: "Unknown", category: "growth" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius", category: "action" },
  { text: "You must do the things you think you cannot do.", author: "Eleanor Roosevelt", category: "courage" },
  { text: "Courage is not the absence of fear, but the triumph over it.", author: "Nelson Mandela", category: "courage" },
  { text: "Faith is taking the first step even when you don't see the whole staircase.", author: "Martin Luther King Jr.", category: "faith" },
  { text: "Be still, and know.", author: "Psalm 46:10 (paraphrase)", category: "faith" },
  { text: "Trust the process, not just the outcome.", author: "Unknown", category: "patience" },
  { text: "Patience is not the ability to wait, but the ability to keep a good attitude while waiting.", author: "Joyce Meyer", category: "patience" },
  { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche", category: "purpose" },
  { text: "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.", author: "Steve Jobs", category: "purpose" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb", category: "action" },
  { text: "Do not wait to strike till the iron is hot; but make it hot by striking.", author: "William Butler Yeats", category: "action" },
  { text: "Money grows on the tree of persistence.", author: "Japanese Proverb", category: "finance" },
  { text: "A budget is telling your money where to go instead of wondering where it went.", author: "Dave Ramsey", category: "finance" },
  { text: "It's not your salary that makes you rich, it's your spending habits.", author: "Charles A. Jaffe", category: "finance" },
  { text: "Out of debt, out of danger.", author: "Proverb", category: "finance" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin", category: "discipline" },
];
