export type LibraryQuote = { text: string; author: string; category: string };

export const QUOTE_CATEGORIES: { slug: string; label: string; blurb: string }[] = [
  { slug: "discipline", label: "Discipline", blurb: "Doing what needs doing, especially when you don't feel like it." },
  { slug: "habits", label: "Habits & Consistency", blurb: "Small actions, repeated, that quietly shape a life." },
  { slug: "resilience", label: "Resilience", blurb: "Getting back up — again and again." },
  { slug: "courage", label: "Courage", blurb: "Acting rightly in the presence of fear." },
  { slug: "wisdom", label: "Wisdom", blurb: "Seeing clearly and choosing well." },
  { slug: "faith", label: "Faith", blurb: "Trust in God beyond what you can see." },
  { slug: "purpose", label: "Purpose & Meaning", blurb: "Knowing why you do what you do." },
  { slug: "success", label: "Success & Achievement", blurb: "Building something worth building." },
  { slug: "leadership", label: "Leadership", blurb: "Serving, guiding, and taking responsibility." },
  { slug: "money", label: "Money & Wealth", blurb: "Earning, saving, and spending with wisdom." },
  { slug: "time", label: "Time", blurb: "The one resource you can't earn back." },
  { slug: "mindset", label: "Mindset", blurb: "How you think shapes what you become." },
  { slug: "gratitude", label: "Gratitude", blurb: "Noticing what you already have." },
  { slug: "love", label: "Love & Relationships", blurb: "Loving people well." },
  { slug: "health", label: "Health & Body", blurb: "Caring for the body you live in." },
  { slug: "learning", label: "Learning & Knowledge", blurb: "Staying a student for life." },
  { slug: "character", label: "Character & Integrity", blurb: "Who you are when no one is watching." },
  { slug: "humility", label: "Humility", blurb: "Seeing yourself accurately." },
  { slug: "patience", label: "Patience", blurb: "Trusting the timing of good things." },
  { slug: "failure", label: "Failure & Mistakes", blurb: "What falling teaches you." },
  { slug: "change", label: "Change", blurb: "Growing through the seasons of life." },
  { slug: "focus", label: "Focus", blurb: "Giving your best attention to what matters most." },
  { slug: "hope", label: "Hope", blurb: "Believing tomorrow can be better." },
  { slug: "self-mastery", label: "Self-Mastery & Recovery", blurb: "Ruling yourself — the hardest and best victory." },
  { slug: "stoicism", label: "Stoic Wisdom", blurb: "Timeless lessons from the Stoic philosophers." },
  { slug: "african-proverbs", label: "African Proverbs", blurb: "Wisdom passed down across generations." },
  { slug: "work", label: "Work & Excellence", blurb: "Doing your work well, as an offering." },
  { slug: "happiness", label: "Happiness & Contentment", blurb: "Finding joy in the life you have." },
  { slug: "peace", label: "Peace", blurb: "Stillness of mind and spirit." },
  { slug: "friendship", label: "Friendship", blurb: "The people who walk with you." },
];
